// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_richesse_iii = "CgkI6LzEr7kGEAIQCA"; // <GPGSID>
        public const string achievement_matre_du_monde_i = "CgkI6LzEr7kGEAIQCQ"; // <GPGSID>
        public const string achievement_voyageur_i = "CgkI6LzEr7kGEAIQAw"; // <GPGSID>
        public const string achievement_tuning = "CgkI6LzEr7kGEAIQDw"; // <GPGSID>
        public const string achievement_blind = "CgkI6LzEr7kGEAIQFQ"; // <GPGSID>
        public const string achievement_hype_beast_iii = "CgkI6LzEr7kGEAIQDg"; // <GPGSID>
        public const string achievement_richesse_i = "CgkI6LzEr7kGEAIQBg"; // <GPGSID>
        public const string achievement_voyageur_iii = "CgkI6LzEr7kGEAIQBQ"; // <GPGSID>
        public const string achievement_matre_du_monde_iii = "CgkI6LzEr7kGEAIQCw"; // <GPGSID>
        public const string achievement_intouchable = "CgkI6LzEr7kGEAIQFA"; // <GPGSID>
        public const string achievement_cosplayer = "CgkI6LzEr7kGEAIQEw"; // <GPGSID>
        public const string achievement_accro = "CgkI6LzEr7kGEAIQEA"; // <GPGSID>
        public const string achievement_poussezvous = "CgkI6LzEr7kGEAIQEg"; // <GPGSID>
        public const string achievement_hype_beast_ii = "CgkI6LzEr7kGEAIQDQ"; // <GPGSID>
        public const string event_first_connection = "CgkI6LzEr7kGEAIQAQ"; // <GPGSID>
        public const string achievement_voyageur_ii = "CgkI6LzEr7kGEAIQBA"; // <GPGSID>
        public const string achievement_matre_du_monde_ii = "CgkI6LzEr7kGEAIQCg"; // <GPGSID>
        public const string achievement_i_will_survive = "CgkI6LzEr7kGEAIQEQ"; // <GPGSID>
        public const string achievement_hype_beast_i = "CgkI6LzEr7kGEAIQDA"; // <GPGSID>
        public const string achievement_richesse_ii = "CgkI6LzEr7kGEAIQBw"; // <GPGSID>

}

